# zsh setup, modified from ~/.bash_profile
#
export TERM=xterm-256color

# get directory this script is in
SOURCE=${(%):-%N}
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
ZDOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# path extensions for brew and cargo
export PATH="$HOME/.linuxbrew/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# neovim setup
alias vim=nvim
export EDITOR=nvim

# up arrow readline completion
echo '# arrow up
"\e[A":history-search-backward
## arrow down
"\e[B":history-search-forward' > ~/.inputrc

# aliases
alias cleanswap='rm -rf /var/tmp/*.swp'
alias cleankernels="dpkg --list | grep linux-image | awk '{ print $2 }' | sort -V | sed -n '/'`uname -r`'/q;p' | xargs sudo apt-get -y purge"

type pbcopy >/dev/null 2>&1 || alias pbcopy='xsel --clipboard --input'
type pbpaste >/dev/null 2>&1 || alias pbpaste='xsel --clipboard --output'

# # fasd init
# eval "$(fasd --init auto)"

### antigen and related config {{{
# config for fancy prompt
source $ZDOT_DIR/antigen/antigen.zsh

antigen use oh-my-zsh
antigen theme https://gist.github.com/nweddle/e456229c0a773c32d37b.git agnoster-newline
antigen bundle common-aliases
antigen bundle fasd
antigen bundle git
antigen bundle gitfast
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle sudo
antigen bundle colored-man-pages
antigen bundle copydir
antigen bundle copyfile

antigen apply

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_CTRL_R_OPTS='--sort'

# do this extra last because other changes to te prompt can clobber it
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ] || [ "$TERM_PROGRAM" = "iTerm.app" ]; then
    source ~/.iterm2_shell_integration.`basename $SHELL`
fi
