#!/usr/bin/env zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# source etc profile for wide compatibility with other unixes . /etc/profile
# get directory this script is in
SOURCE=${(%):-%N}
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
export ZDOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# OS-specific
case "$(uname -s)" in
    Linux*)
      export GOROOT=/usr/lib/go/
      export BROWSER=firefox.desktop
      ;;
    Darwin*)
      . /usr/local/opt/asdf/asdf.sh
      export BROWSER="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
      eval "$(brew shellenv)"
    ;;
esac

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export PATH=/usr/lib/go/bin:$PATH

export PATH=$HOME/.emacs.d/bin:$PATH
export PATH=$HOME/Library/Python/3.8/bin:$PATH
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$(npm bin -g):$PATH"
export PATH=$HOME/bin:$PATH

export EDITOR="vi"


# no-wait for the shortest alias
export ALTERNATE_EDITOR=""
alias e="emacsclient -n"
alias emc="emacsclient -n"
alias emcc="emacsclient -c"
export EDITOR="emacsclient -t"        # $EDITOR opens in terminal
export GIT_EDITOR='emacsclient -t'
export K9S_EDITOR='emacsclient' # -t is kinda broken w/ yamls for some reason
export VISUAL='emacsclient'  # $VISUAL opens in GUI mode
# when inside of emacs, DO NOT USE tty, always open in the editor itself
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
  export EDITOR='emacsclient'
  export GIT_EDITOR='emacsclient'
fi

# aliases
alias cleanswap='rm -rf /var/tmp/*.swp'
alias reload='. ~/.zshrc && antigen reset && src'
alias venv='source venv/bin/activate'
alias gst='git status'
alias gapa='git add -p'
alias gcpa='git checkout -p'
alias b='brexctl'
fswatch() { while inotifywait --exclude .swp -e modify -r .; do $@; done; }

type pbcopy >/dev/null 2>&1 || alias pbcopy='xsel --clipboard --input'
type pbpaste >/dev/null 2>&1 || alias pbpaste='xsel --clipboard --output'

# elixir dev vars
export DATABASE_HOST=localhost

### antigen - zsh package manager {{{
source $ZDOT_DIR/antigen/antigen.zsh

antigen use oh-my-zsh
antigen theme romkatv/powerlevel10k # prompt with newline
antigen bundle archlinux
antigen bundle aws
antigen bundle bazel
antigen bundle colored-man-pages
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle copyfile
antigen bundle copypath
antigen bundle docker
antigen bundle fasd # for z
antigen bundle fzf
antigen bundle gcloud
antigen bundle gitfast # no aliases, just fast bits for prompt integration
antigen bundle golang
antigen bundle jira
antigen bundle kubectl
antigen bundle macos
antigen bundle minikube
antigen bundle sudo
antigen bundle DarrinTisdale/zsh-aliases-exa
antigen bundle zsh-interactive-cd # uses fzf
antigen bundle zsh-users/zsh-history-substring-search # up arrow
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

unsetopt HIST_VERIFY

# setup for external tools
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_CTRL_R_OPTS='--sort'

eval "$(fasd --init auto)"
eval "$(direnv hook zsh)"
eval "$(nodenv init -)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
